#服务器配置
server:
  port: 8080

spring:
  #数据源
  datasource:
    url: jdbc:mysql://localhost:3306/echarts?serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: root
    password: cao123

#  #视图层控制
#  mvc:
#    static-path-pattern: /static/**
#    view:
#      prefix: classpath:/templates/
#      suffix: .html

