server:
  port:8080

spring:
  datasource:
    username: root
    password: cao123
    url: jdbc:mysql://localhost:3306/jiuyun?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver